### ISSUE TITLE
ネストした書き方にする

### ISSUE THREAD

**Issue by keigo0331** [WataruTakahasi/ECsite#21]
SCSSの特徴としてネストさせて書けるのでそれを使う

```scss
product {
  &-header {
    ...
  }
}
```

https://github.com/WataruTakahasi/ECsite/blob/b1d5f8a5b955e98a329f0fd2757f630c94e8f1f4/app/assets/stylesheets/products.scss#L1

**Comment by WataruTakahasi** [comment]
済み
